# Generated by Django 3.0.4 on 2020-04-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hambuerguesa',
            new_name='Hamburguesa',
        ),
        migrations.RenameModel(
            old_name='Hambuerguesa_Ingrediente',
            new_name='Hamburguesa_Ingrediente',
        ),
    ]
