# Generated by Django 3.0.5 on 2020-04-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200420_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
