# Generated by Django 3.0.5 on 2020-04-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200420_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamburguesa_ingrediente',
            old_name='hamburguesa_id',
            new_name='id_hamburguesa',
        ),
        migrations.RenameField(
            model_name='hamburguesa_ingrediente',
            old_name='ingrediente_id',
            new_name='id_ingrediente',
        ),
    ]
