# Generated by Django 3.0.5 on 2020-04-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200420_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.CharField(default='  ', max_length=200),
        ),
    ]
