# Generated by Django 3.0.5 on 2020-04-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hamburguesa_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamburguesa',
            name='ingredientes',
        ),
        migrations.AlterField(
            model_name='hamburguesa_ingrediente',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False),
        ),
    ]
