# Generated by Django 3.0.5 on 2020-04-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200421_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hamburguesa_ingrediente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
