# Generated by Django 3.0.5 on 2020-04-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200421_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hamburguesa_ingrediente',
            name='id_hamburguesa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hamburguesa_ingrediente',
            name='id_ingrediente',
            field=models.IntegerField(),
        ),
    ]
