# Generated by Django 3.0.5 on 2020-04-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200422_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
