# Generated by Django 3.0.5 on 2021-04-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200505_0333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hamburguesa',
            new_name='Hamburger',
        ),
        migrations.RenameModel(
            old_name='Hamburguesa_Ingrediente',
            new_name='Hamburger_Ingredient',
        ),
        migrations.RenameModel(
            old_name='Ingrediente',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='hamburger',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hamburger',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='hamburger',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hamburger',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='hamburger_ingredient',
            old_name='id_hamburguesa',
            new_name='id_hamburger',
        ),
        migrations.RenameField(
            model_name='hamburger_ingredient',
            old_name='id_ingrediente',
            new_name='id_ingredient',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='nombre',
            new_name='name',
        ),
    ]
